### ISSUE TITLE
ddem bin filtering too strict for CL_NPI

### ISSUE THREAD

**Issue by adehecq** [adehecq/ragmac_xdem#71]
During the hypsometric fit, some elevation bins are filtered by the NMAD filter. This seems too strict as it removes valid bins
![image](https://user-images.githubusercontent.com/3285905/160642808-a8595068-4b80-4b3a-ab23-f952ff71457c.png)

**Comment by adehecq** [comment]
A quick investigation shows that the minimum dh value is -70, while the NMAD is ~3.4. This means a factor of about 20 between the NMAD and maximum value, way beyond the factor 5 set as default.
A larger value could be set, but then the filter would most likely never be used.

**Comment by dshean** [comment]
What happens if you disable this filter?  

I would think some combination of individual bin count/area and individual bin stats could be used to exclude potentially problematic bins, rather than a global filter.  

Or maybe some "rolling bin" filter that considers values from n adjacent bins to evaluate whether a given bin is problematic.
